# Generated by Django 5.2.17 on 2026-09-27 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistaVanguardia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('movimiento', models.CharField(help_text='Ej: Arte Sonoro, Fluxus, BioArte, Futurismo', max_length=100)),
                ('pais', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Artista de Vanguardia',
                'verbose_name_plural': 'Artistas de Vanguardia',
            },
        ),
        migrations.CreateModel(
            name='InstalacionArtistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('anio_exposicion', models.IntegerField(verbose_name='Año de Exposición')),
                ('lugar_galeria', models.CharField(help_text='Galería, Museo o Espacio público', max_length=200)),
                ('descripcion', models.TextField()),
                ('artistas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instalaciones', to='instalaciones.artistavanguardia')),
            ],
            options={
                'verbose_name': 'Instalación Artística',
                'verbose_name_plural': 'Instalaciones Artísticas',
            },
        ),
    ]
