# Generated by Django 5.2.17 on 2026-09-27 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistaCompositor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('pais', models.CharField(max_length=100)),
                ('biografia', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlbumExperimental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('genero', models.CharField(max_length=100)),
                ('anio', models.IntegerField(verbose_name='Año de Lanzamiento')),
                ('formato', models.CharField(choices=[('VINYL', 'Vinilo'), ('CASSETTE', 'Casete'), ('CD', 'CD'), ('DIGITAL', 'Digital / Bandcamp'), ('CINTA_MAGN', 'Cinta Magnética / Reel-to-Reel')], default='DIGITAL', max_length=20)),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albumes', to='musica_experimental.artistacompositor')),
            ],
        ),
    ]
