# Generated by Django 5.2.17 on 2026-09-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica_experimental', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='albumexperimental',
            options={'verbose_name': 'Álbum Experimental', 'verbose_name_plural': 'Álbumes Experimentales'},
        ),
        migrations.AlterModelOptions(
            name='artistacompositor',
            options={'verbose_name': 'Artista / Compositor', 'verbose_name_plural': 'Artistas y Compositores'},
        ),
        migrations.AddField(
            model_name='albumexperimental',
            name='portada_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de Portada'),
        ),
    ]
