# Generated by Django 5.2.17 on 2026-09-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica_experimental', '0002_alter_albumexperimental_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albumexperimental',
            name='portada_url',
        ),
        migrations.AddField(
            model_name='albumexperimental',
            name='portada',
            field=models.URLField(default='https://picsum.photos/300/300', max_length=500),
        ),
    ]
